kind: Deployment
apiVersion: apps/v1
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        deployment: registry
    spec:
      containers:
        - name: registry
          image: 'quay.io/devspaces/devfileregistry-rhel8:3.17'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: index-volume
              mountPath: /var/www/html/index
              subPath: index
            - name: index-volume
              mountPath: /var/www/html/devfiles/ansible__ansible-demo/devworkspace-custom.yaml
              subPath: devworkspace-custom.yaml
          imagePullPolicy: Always
      volumes:
        - name: index-volume
          configMap:
            name: files
      restartPolicy: Always